# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Coveralls Report

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        IDEA_VERSION: 2024.2.1
      run: xvfb-run ./gradlew test
    - name: Coveralls
      uses: coverallsapp/github-action@v2.3.0
      with:
        github-token:  ${{ secrets.COVERALLS_TOKEN }}
