# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: EAP

on:
  schedule:
    - cron:  '0 6 */14 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        IDEA_VERSION: LATEST-EAP-SNAPSHOT
        GRAMMAR_KIT_VERSION: 2019.3
        IDEA_SOURCES: false
      run: xvfb-run ./gradlew build
